shared:
  image: node:6
jobs:
  main:
    steps:
      - set-unstable: |
          if [ "$COVERAGE" -lt 95 ]
            then curl -X PUT -H "Authorization: Bearer $SD_TOKEN" -H "Content-Type: application/json" -d '{"status": "UNSTABLE", "statusMessage": "this build is unstable"}' "${SD_BUILD_URL}"
          fi
      - echo: echo "This build status is set as Unstable and will not trigger the next build"
    environment:
        COVERAGE: 90
    requires:
      - ~commit
  publish:
    steps:
      - echo: echo "This will not be triggered"
    requires:
      - main
